### ISSUE TITLE
Поправить рамки блоков с серым фоном

### ISSUE THREAD

**Issue by lizakoles** [Practiq-io/company-landing#23]
**Зачем нам это надо**
Для улучшения вида лэйндинга 

**Что нужно сделать**
Удлинить рамки серого фона до начала и конца страницы с боков 
Пример:
![Снимок экрана 2020-06-12 в 10 10 03](https://user-images.githubusercontent.com/46873772/84486167-e6784380-ac94-11ea-9724-f613e281f8c9.png)

**Comment by madrobothere** [comment]
# Done
