### ISSUE TITLE
Сократить время изменения примеров заданий (первый блок)

### ISSUE THREAD

**Issue by lizakoles** [Practiq-io/company-landing#24]
**Зачем нам это надо**
Что бы пользователь мог за более короткое время понять что мы предоставляем не один сервис (например только "build miscorservice"). Сейчас период изменения занимает примерно 10 секунд от начала до конца - за это время обычно пользователи уже перешли на следующую страницу

**Что нужно сделать**
Сократить время - например когда в правой консоли уже напечатался код для задания, можно не стирать его по одной букве, а удалить в целом, что бы уже мог начаться печататься код следующего примера

**Comment by Timson-Saru** [comment]
принято, проработаем

**Comment by Timson-Saru** [comment]
Fixed.
