### ISSUE TITLE
проблема со слайдером в 'What we can build for you"

### ISSUE THREAD

**Issue by lizakoles** [Practiq-io/company-landing#25]
**Зачем нам это надо**
Проблема использования слайдера - он работает только нажимая на нижние кнопочки, которые плохо видно. Как пользователь, я даже не вижу что там есть еще варианты

**Что нужно сделать**
Улучшить смену заданий слайдером (трэкпэдом) или поставить стрелочку, что бы было более понятно, что там есть еще варианты заданий  

![Снимок экрана 2020-06-12 в 10 16 33](https://user-images.githubusercontent.com/46873772/84486896-ee84b300-ac95-11ea-8e63-822b55757b1e.png)

**Comment by Timson-Saru** [comment]
добавил кнопки для навигации карточек
